### ISSUE TITLE
This fork isn't published in the maven central repo

### ISSUE THREAD

**Issue by mabdallah450** [F0RIS/sweet-alert-dialog#1]
Please, can you publish this fork in the maven central repo to be able to compile it in my project `build.gradle `

**Comment by F0RIS** [comment]
I know, will upload it asap. Never did it before

**Comment by F0RIS** [comment]
@mabdallah450 http://search.maven.org/#search%7Cga%7C1%7Ccom.github.f0ris.sweetalert
