### ISSUE TITLE
PROGRESS_TYPE dialog height

### ISSUE THREAD

**Issue by karishmapujara** [F0RIS/sweet-alert-dialog#10]
Hello

There is space below Loading text. So what can i do to remove it?

![capture](https://user-images.githubusercontent.com/3817026/31305961-4048b0ce-ab63-11e7-867f-1f94384678da.PNG)

`Here is my code

        SweetAlertDialog pDialog = new SweetAlertDialog(Pilot.this, SweetAlertDialog.PROGRESS_TYPE);

        @Override
        protected void onPreExecute() {
            super.onPreExecute();

            pDialog.getProgressHelper().setBarColor(Color.parseColor("#A5DC86"));
            pDialog.setTitle("Loading");
            pDialog.setCancelable(false);
            pDialog.show();
        }`

**Comment by F0RIS** [comment]
This is know bug, don't have time to fix it. If u need PROGRESS_TYPE and don't need features which were added in this fork u can use original repo https://github.com/pedant/sweet-alert-dialog

**Comment by F0RIS** [comment]
@karishmapujara next version in on release process)

**Comment by karishmapujara** [comment]
Hello sir
Can you tell me when the next version is available?
Thanks

**Comment by F0RIS** [comment]
@karishmapujara several hours

**Comment by karishmapujara** [comment]
ok
