### ISSUE TITLE
Button Text

### ISSUE THREAD

**Issue by karishmapujara** [F0RIS/sweet-alert-dialog#11]
Hello 
I have problems in Button text. All text is not displaying.

Three buttons are: Cancel,PRESCRIPTION,BILL

![capture](https://user-images.githubusercontent.com/3817026/31491451-fd48a35a-af64-11e7-887b-25e279069a54.PNG)

**Comment by alexandreleick** [comment]
Hi !
I use this library in my app and it beautiful ! But the button text is not displaying :(
It's possible to fix this bug please ? :)

Thanks you
