### ISSUE TITLE
Large padding bottom 

### ISSUE THREAD

**Issue by severinewillez** [F0RIS/sweet-alert-dialog#16]
There is large padding bottom when the dialog type is SweetAlertDialog.PROGRESS_TYPE. Is it possible to change this size manually ? And if not, can you fix this problem ? Thanks a lot.

**Comment by F0RIS** [comment]
Can you show screenshot and your code?

**Comment by MarceloFreitasx** [comment]
![photo_2018-04-20_11-02-30](https://user-images.githubusercontent.com/6873417/39055332-5a81a462-448a-11e8-8571-cab6c7f1f657.jpg)

Same here

**Comment by F0RIS** [comment]
@MarceloFreitasx code please. Cuz in sampes it works fine

**Comment by MarceloFreitasx** [comment]
`SweetAlertDialog dialog = new SweetAlertDialog(this, SweetAlertDialog.PROGRESS_TYPE);`
`dialog.getProgressHelper().setBarColor(Color.parseColor("#ff4e5a"));`
`dialog.setTitleText("Carregando");`
`dialog.setCancelable(false);`
`dialog.show();`

**Comment by F0RIS** [comment]
Seems you use old version 1.5.1. Switch to new -> 1.5.2

**Comment by severinewillez** [comment]
@F0RIS Thanks, I was using the old version. It works perfectly with version 1.5.2 :)
