### ISSUE TITLE
Error on Building (Marge Manifest)

### ISSUE THREAD

**Issue by aldiand** [F0RIS/sweet-alert-dialog#17]
Got this error :
> Error:Execution failed for task ':app:processDebugManifest'.
> > Manifest merger failed : Attribute application@icon value=(@mipmap/ic_launcher) from AndroidManifest.xml:12:9-43
>   	is also present at [com.pnikosis:materialish-progress:1.0] AndroidManifest.xml:13:9-45 value=(@drawable/ic_launcher).
>   	Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:10:5-61:19 to override.

Maybe need to update materialish-progress

**Comment by F0RIS** [comment]
Do what error messages suggests. For more info look over original repo issues. It's common problem.
