### ISSUE TITLE
Text not wrapping on custom view (more than 5 lines)

### ISSUE THREAD

**Issue by ralphgabrielle** [F0RIS/sweet-alert-dialog#18]
Im not sure if its because of the framelayout, instead of linear layout, but overall, it should work the way it is implemented, but for some reason, if you add a text view at setCustomView(textView)   with more than 5 lines of text, it only shows the first 4 lines and omit the rest. 

Any fix ?  Thanks

**Comment by F0RIS** [comment]
Seems that this bug was in original repo, I haven't fix that, I tryid though
