### ISSUE TITLE
Set custom font

### ISSUE THREAD

**Issue by Pho3niX90** [F0RIS/sweet-alert-dialog#2]
Good to see the project went on, have you implemented a method to set custom text/font yet?

**Comment by F0RIS** [comment]
@Pho3niX90 No. I saw that somebody made such pull request to original repo, but I dont have time to apply his code))

**Comment by sajadabasi** [comment]
+1 please add this feature

**Comment by F0RIS** [comment]
You are welcome to do it

**Comment by sajjadintel** [comment]
added
