### ISSUE TITLE
not support com.pnikosis:materialish-progress:1.7

### ISSUE THREAD

**Issue by 3kqing** [F0RIS/sweet-alert-dialog#22]
not support com.pnikosis:materialish-progress:1.7

progressIndeterminate
to
matProg_progressIndeterminate

**Comment by 3kqing** [comment]
please update com.pnikosis:materialish-progress:1.7

**Comment by F0RIS** [comment]
it doesnt break anything else? Why you need that?

**Comment by F0RIS** [comment]
Done https://github.com/F0RIS/sweet-alert-dialog/commit/010892580dee4ec08c65a6f91e495d4cff18ba77
I'm waiting star from you 🙂

**Comment by 3kqing** [comment]
thanks

**Comment by manishakalia** [comment]
Some issue I am facing in my project not support com.pnikosis:materialish-progress:1.7? Any Solution?
