### ISSUE TITLE
I got error on Android 8

### ISSUE THREAD

**Issue by engmmrj** [F0RIS/sweet-alert-dialog#23]
I got error on Android 8 on firebase

 `` Fatal Exception: android.view.WindowManager$BadTokenException
Unable to add window -- token android.os.BinderProxy@17f2660 is not valid; is your activity running?
project.helper.CheckUpdateHelper.showDialogForUpdate ``

This crash is usually caused by your app trying to display a dialog using a previously-finished Activity as a context. For example, this can happen if an Activity triggers an AsyncTask that tries to display a dialog when it is finished, but the user navigates back from the Activity before the task is completed.

External resources
[Android – Displaying Dialogs From Background Threads
](http://dimitar.me/android-displaying-dialogs-from-background-threads/)Error : [BinderProxy@45d459c0 is not valid; is your activity running?](https://stackoverflow.com/questions/7811993/error-binderproxy45d459c0-is-not-valid-is-your-activity-running)

**Comment by F0RIS** [comment]
Does your app crashes after that? I have such logs too, but it doesnt affect how my app works

**Comment by engmmrj** [comment]
My app crash after that , Firebase said app creached

**Comment by F0RIS** [comment]
I see such errors without crash. May be you should try reproduce this error. Just try do something that may generate error and check logs
