### ISSUE TITLE
Custom style

### ISSUE THREAD

**Issue by rmushfiqur2** [F0RIS/sweet-alert-dialog#25]
![image](https://user-images.githubusercontent.com/32337334/45491790-64d84680-b78c-11e8-8530-b3eacacd3021.png)
How to implemrnt this in code ??

**Comment by EleLawliet** [comment]
Creas un VIEW ( layout ).
Luego lo agregas (SweetAlert.setCustonView(R.layout.tuview))
Inflas la vista y listo

**Comment by F0RIS** [comment]
@rmushfiqur2 https://github.com/F0RIS/sweet-alert-dialog/blob/master/sample/src/main/java/cn/pedant/SweetAlert/sample/SampleActivity.java#L240
