### ISSUE TITLE
Change the width of the dialog box

### ISSUE THREAD

**Issue by huseyin39** [F0RIS/sweet-alert-dialog#29]
There isn't any possibility to set manually the width of the box right?

**Comment by F0RIS** [comment]
@huseyin39 you can try set here wrap_content and then it will adjust to your cutom view width
https://github.com/F0RIS/sweet-alert-dialog/blob/master/library/src/main/res/layout/alert_dialog.xml#L164

**Comment by huseyin39** [comment]
@F0RIS  Thanks !

**Comment by F0RIS** [comment]
@huseyin39 write if it solves your problem, bcz I changed that line for my project too, may be this change should be released
