### ISSUE TITLE
Error building : duplicate Attributes

### ISSUE THREAD

**Issue by carvalho2707** [F0RIS/sweet-alert-dialog#33]
Hi,

The latest version fails to build due to conflict of duplicated attributes 
pivotX and pivotY were introduced in the latest versions of constraint layout.

`values.xml:6875: error: duplicate value for resource 'attr/pivotX' with config ''.`
`values.xml:6875: error: duplicate value for resource 'attr/pivotY' with config ''.`

**Comment by carvalho2707** [comment]
Anything on this @F0RIS?

Can you rename this parameters so we can use this library with the latest constraint layout dependency?

**Comment by F0RIS** [comment]
I dont have time for changing and checking if it breakes something

**Comment by carvalho2707** [comment]
Hi again @F0RIS , i've created a PR for this issue 😄 
Please have a look , it's properly tested

**Comment by carvalho2707** [comment]
Fixed in #36
