### ISSUE TITLE
Content text cut off

### ISSUE THREAD

**Issue by jaymin19syno** [F0RIS/sweet-alert-dialog#34]
Text of the content is not showing as the string is. It will cut some text from the end. I have tested on moto g6 play and one plus five.

The original string is : "Thank you for posting your load.\nPlease be on the standby for transports associate bid." I have declared string in string.xml file.
![sweet_alert_oneplus](https://user-images.githubusercontent.com/46773555/56808182-7b7c6b00-684e-11e9-8844-752dd700ae97.png)
![sweet_alert_g6](https://user-images.githubusercontent.com/46773555/56808183-7b7c6b00-684e-11e9-9b6c-44199946838b.png)

**Comment by vinczu** [comment]
which version do you use? I think it is fixed with 1.5.6

**Comment by jaymin19syno** [comment]
Hello

Thanks for reply. Yes it is fixed with latest version.


Thank you,
Warm Regards,
Jaymin Patel | Software Engineer – Mobility
Mob. : +91 7203840830 | E-mail: jaymin.patel@synoverge.com<mailto:jaymin.patel@synoverge.com>
