### ISSUE TITLE
Set full width sweet alert dialog

### ISSUE THREAD

**Issue by Thanushkajayasinghe** [F0RIS/sweet-alert-dialog#35]
Hi,
I'm using sweet alerts for my android app.but it's not getting full width. any way to resolve this? android version :- kitkat.
Thanks.

![IMG_20190502_104227](https://user-images.githubusercontent.com/9781823/57069141-5e81e500-6cf1-11e9-8983-8841f2000c26.jpg)

**Comment by F0RIS** [comment]
@Thanushkajayasinghe 
Hi. You can create custom view, set it width to desired and then insert that custom view in dialog.
Example:
```
final EditText editText = new EditText(act);
LinearLayout linearLayout = new LinearLayout(act);
linearLayout.setOrientation(LinearLayout.VERTICAL);
linearLayout.setLayoutParams(new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT));
linearLayout.addView(editText);

SweetAlertDialog dialog = new SweetAlertDialog(act, SweetAlertDialog.NORMAL_TYPE);
dialog.setCustomView(linearLayout);
dialog.show();
```
