### ISSUE TITLE
cn.pedant.SweetAlert.Rotate3dAnimation

### ISSUE THREAD

**Issue by wilsonhub** [F0RIS/sweet-alert-dialog#42]
E/UncaughtException: java.lang.RuntimeException: Unknown animation name: cn.pedant.SweetAlert.Rotate3dAnimation error:cn.pedant.SweetAlert.Rotate3dAnimation

**Comment by F0RIS** [comment]
this repo package is com.github.f0ris.sweetalert
you wrote in a wrong repo!

**Comment by ghost** [comment]
I got the same error, and I implemented your library not the old one ..
