### ISSUE TITLE
.setCancelable(false) not working. Please add it

### ISSUE THREAD

**Issue by STPLAmrut** [F0RIS/sweet-alert-dialog#44]
new SweetAlertDialog(UserComplaintRegistration.this, SweetAlertDialog.NORMAL_TYPE)
                .setTitleText("a"))
                .setContentText("b")
                .setConfirmText("c")
                .setCancelable(false)
                .setConfirmClickListener(new SweetAlertDialog.OnSweetClickListener() {
                    @Override
                    public void onClick(SweetAlertDialog sDialog) {

                        sDialog.dismiss();
                    }
                })
                .show();

.setCancelable(false) not working. Please add it

**Comment by hamaz562006** [comment]
SweetAlertDialog sDialog = new SweetAlertDialog(UserComplaintRegistration.this,SweetAlertDialog.NORMAL_TYPE);
sDialog.setTitleText("a"));
sDialog.setCancelable(false);

this worked for me
