### ISSUE TITLE
Unknown animation name: cn.pedant.SweetAlert.Rotate3dAnimation when make release app

### ISSUE THREAD

**Issue by fparkar** [F0RIS/sweet-alert-dialog#49]
When I use this while development, all was fine.

For upload, when I make apk on release mode, I get below error.

**_java.lang.RuntimeException: Unknown animation name: cn.pedant.SweetAlert.Rotate3dAnimation error:cn.pedant.SweetAlert.Rotate3dAnimation_**

Any idea why this error is coming? Am I missing anything?

**Comment by ghost** [comment]
Same... any idea how to resolve friend ?

**Comment by rscherf** [comment]
Still seeing this as well, but seems like there isn't interest in fixing this.
