### ISSUE TITLE
dismissWithAnimation issue

### ISSUE THREAD

**Issue by davo417** [F0RIS/sweet-alert-dialog#51]
When I create a dialog instance and call .dismissWithAnimation() the dialog goes useless. If I call .show() again on it does not appear, just got black overlay on the screen. I think this is product of the out animation, in the dismissWithAnimation impl the alpha animation is set on the child view and that alpha never goes back to 1.0f.

**Comment by F0RIS** [comment]
Probably it wasn't designed to call show after dismissing
