### ISSUE TITLE
Dark background not used for Theme.MaterialComponents.DayNight

### ISSUE THREAD

**Issue by ghost** [F0RIS/sweet-alert-dialog#54]
I am using material DayNight theme: 

`<style name="AppTheme" parent="Theme.MaterialComponents.DayNight">`

This theme is set as used always in my custom App class (this clas is set properly in manifest): 

```
public class MyApplication extends Application {

    public void onCreate() {
        super.onCreate();

        AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES);
    }
}
```

The problem is that my app uses dark theme, but this beautiful dialogs has white theme. How to fix that?

**Comment by F0RIS** [comment]
SweetAlertDialog.DARK_STYLE = true;

**Comment by ghost** [comment]
Great, thank you :)
