### ISSUE TITLE
Clarification-Do we have close(X mark at top right) button option 

### ISSUE THREAD

**Issue by vijayakumarmariyappan** [F0RIS/sweet-alert-dialog#59]
Hi @F0RIS , Thanks for the excellent library :)

can I configure alert dialog, like having close(X mark at top right) button option.  Is that feature available to use ! Thanks for your time

I knew that when we tap out of the alert dialog cancels it. but when we show big alert, which occupies the almost entire screen, the user will struggle to close the alert. is there any option so that I can have x mark and tap out option both. Thank you :)

**Comment by F0RIS** [comment]
You can achieve that only by modifying the library

**Comment by vijayakumarmariyappan** [comment]
@F0RIS Thanks :) it could be nice if it is built inside the library 👍
