### ISSUE TITLE
Change button color back to blue

### ISSUE THREAD

**Issue by deechang** [F0RIS/sweet-alert-dialog#9]
Hi,

thank you very much for your work! Still, I have one question: How can I change the button color back to blue? Your version has green buttons, but they don't really work out with my design.

Thank you, keep up the good work!

**Comment by F0RIS** [comment]
For now you can add this lib as module to ur app and edit style. Thats how I use it. Also if you will write some convenient interface to make what u want. Send it to me, I will appreciate  🙂

**Comment by kdblue** [comment]
@F0RIS , I want to contribute in this project and i know how to solve this error.

**Comment by F0RIS** [comment]
@kdblue no problem, do PR, I am and other will appreciate that!

**Comment by F0RIS** [comment]
@kdblue any updates?

**Comment by carvalho2707** [comment]
@F0RIS @kdblue I've submitted a PR that allows this

**Comment by F0RIS** [comment]
@carvalho2707 hey, can you investigate why in last version max width of the dialog became too small. Even short text can't be displayed on the buttons.

**Comment by carvalho2707** [comment]
@F0RIS I'll do that soon
